import type { Metadata } from "next";
import { LayoutProps } from "@/lib/@types/props";

export const metadata: Metadata = {
    title: "Figma Online",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps) {
    return (
        <html lang="en">
            <body>
                {children}
            </body>
        </html>
    );
}
